# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.10.10

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-docstring-first
        # -   id: check-json
        -   id: check-yaml
        -   id: requirements-txt-fixer
        -   id: double-quote-string-fixer

# -   repo: https://github.com/pycqa/isort
#     rev: 5.10.1
#     hooks:
#         -   id: isort
#             name: isort (python)
#             files: "imports.py"
#             args: [--settings-path=pyproject.toml]

# -   repo: https://github.com/asottile/reorder_python_imports
#     rev: v3.0.1
#     hooks:
#         -   id: reorder-python-imports
#             args: [--py3-plus]

# -   repo: https://github.com/ambv/black
#     rev: 21.12b0
#     hooks:
#     - id: black

# -   repo: https://github.com/sourcery-ai/sourcery
#     rev: v0.11.1 # Get the latest tag from https://github.com/sourcery-ai/sourcery/tags
#     hooks:
#         - id: sourcery
#         # - args: [--in-place]  Automatically apply the refactorings in the hook

# -   repo: https://gitlab.com/pycqa/flake8
#     rev: 3.9.2
#     hooks:
#     - id: flake8

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.910-1
#     hooks:
#     -   id: mypy
#         additional_dependencies: [types-all]

# -   repo: https://github.com/jonasbb/pre-commit-latex-hooks
#     rev: v1.2.0
#     hooks:
#         -   id: american-eg-ie
#         -   id: cleveref-capitalization
#         -   id: csquotes
#         -   id: no-space-in-cite
