---
doctype: jou
# editor: visual
# jupyter: study1
lang: en-US
indent: true
font: Times New Roman
mainfont: Times New Roman
fontsize: 12pt
text-align: right
date: "`r format(Sys.time(), '%B %d, %Y')`"
title: "Bias in Candidate Sourcing Communication"
subtitle: "Investigating Stereotypical Gender- And Age-Related Frames in Online Job Advertisements at the Sectoral Level"
shorttitle: "Bias in Candidate Sourcing Communication"
author:
    - M.F.A. Noon, PhD:
        email: "noon.abdulqadir@uva.nl"
        institute: [UvA]
        correspondence: true
        orcid: "0000-0002-6243-9241"
    # - email: "noon.abdulqadir@uva.nl"
    # - orcid: "0000-0002-6243-9241"
    # - url: "https://noon-abdulqadir.com/"
    # - twitter: "https://twitter.com/NoonAbdulqadir"
    # - github: "https://github.com/noon-abdulqadir"
    # - linkedin: "https://www.linkedin.com/in/noon-abdulqadir/"
    # - researchgate: "https://www.researchgate.net/profile/Noon-Abdulqadir"
institute:
    - UvA: "University of Amsterdam, Amsterdam School of Communication Research (ASCoR), Postbus 15791, 1001 NG Amsterdam."
leftheader: "BIAS IN CANDIDATE SOURCING COMMUNICATION"
authors_note: |
    Correspondence concerning this article should be addressed to M.F.A. Noon, Postbus 15791, 1001 NG Amsterdam. Email: noon.abdulqadir@uva.nl
abstract: "Studies show that the extent to which job advertisements contain stereotypical wordings correlates with the level of segregation in an occupational domain. However, limited research links the framing of job ads to social category-based occupational segregation at the macro sectoral level. Guided by the stereotype content model, the present study operationalizes stereotypical social categorization frames in candidate sourcing communication and investigates their presence in job ads from occupational sectors with varying gender and age segregation. An automated (supervised) content analysis was conducted on a dataset of online job ads (*n*=17,050). Results indicate warmth-related frames are most observed in ads from female-dominated (vs. male-dominated and mixed-gender) sectors. Conversely, competence-related frames are most observed in ads from male-dominated (vs. female-dominated) and younger worker-dominated (vs. older worker-dominated and mixed-age) sectors. Taken together, we present an operationalization of stereotypical warmth- and competence-related frames in early employer communication and posit that social categorization framing may be at play."
keywords: "Stereotype content model, social categorization frames, horizontal occupational segregation, supervised content analysis"
format:
    pdf:
        mainfont: Times New Roman
        fontsize: 12pt
        text-align: right
        latex_engine: pdflatex
    docx:
        mainfont: Times New Roman
        fontsize: 12pt
        text-align: right
    html:
        mainfont: Times New Roman
        fontsize: 12pt
        text-align: right
        html-math-method: katex
        html-math-output: eps
        html-math-style: display
        html-math-size: "100%"
        html-math-color: "black"
        html-math-background-color: "white"
        code-tools: true
        code-line-numbers: true
        self-contained: true
output:
    pdf_document:
        pandoc_args:
            - --csl=apa.csl
            - --filter=pandoc-crossref
            - --reference-doc=word_template_apa7.docx
            - --csl=Extras/clinical-biochemistry.csl
            - --citation-abbreviations=Extras/abbreviations.json
            - --lua-filter=Extras/scholarly-metadata.lua
            - --lua-filter=Extras/author-info-blocks.lua
        toc_depth: 0
        template: "template.tex"
        extra_dependencies: "subfig"
        latex_engine: pdflatex
        keep-ipynb: true
        keep-md: true
        keep_tex:  true
        number_sections: true
    word_document:
        pandoc_args:
            - --csl=apa.csl
            - --filter=pandoc-crossref
            - --reference-doc=word_template_apa7.docx
            - --csl=Extras/clinical-biochemistry.csl
            - --citation-abbreviations=Extras/abbreviations.json
            - --lua-filter=Extras/scholarly-metadata.lua
            - --lua-filter=Extras/author-info-blocks.lua
        # reference_doc: word_template_apa7.docx
        keep-ipynb: true
        keep-md: true
        keep_tex:  true
        number_sections: true
    html_document:
        pandoc_args:
            - --csl=apa.csl
            - --filter=pandoc-crossref
            - --reference-doc=word_template_apa7.docx
            - --csl=Extras/clinical-biochemistry.csl
            - --citation-abbreviations=Extras/abbreviations.json
            - --lua-filter=Extras/scholarly-metadata.lua
            - --lua-filter=Extras/author-info-blocks.lua
        keep-ipynb: true
        keep-md: true
        keep_tex:  true
        number_sections: true
    latex_document:
        pandoc_args:
            - --csl=apa.csl
            - --filter=pandoc-crossref
            - --reference-doc=word_template_apa7.docx
            - --csl=Extras/clinical-biochemistry.csl
            - --citation-abbreviations=Extras/abbreviations.json
            - --lua-filter=Extras/scholarly-metadata.lua
            - --lua-filter=Extras/author-info-blocks.lua
        keep-ipynb: true
        keep-md: true
        keep_tex:  true
        number_sections: true
    bookdown::pdf_book:
        pandoc_args:
            - --csl=apa.csl
            - --filter=pandoc-crossref
            - --reference-doc=word_template_apa7.docx
            - --csl=Extras/clinical-biochemistry.csl
            - --citation-abbreviations=Extras/abbreviations.json
            - --lua-filter=Extras/scholarly-metadata.lua
            - --lua-filter=Extras/author-info-blocks.lua
        toc_depth: 1
        template: "template.tex"
        extra_dependencies: "subfig"
        latex_engine: pdflatex
        keep-ipynb: true
        keep-md: true
        keep_tex:  true
        number_sections: true
    bookdown::word_document2:
        pandoc_args:
            - --csl=apa.csl
            - --filter=pandoc-crossref
            - --reference-doc=word_template_apa7.docx
            - --csl=Extras/clinical-biochemistry.csl
            - --citation-abbreviations=Extras/abbreviations.json
            - --lua-filter=Extras/scholarly-metadata.lua
            - --lua-filter=Extras/author-info-blocks.lua
        # reference_doc: word_template_apa7.docx
        keep-ipynb: true
        keep-md: true
        keep_tex:  true
        number_sections: true
    bookdown::html_document2:
        pandoc_args:
            - --csl=apa.csl
            - --filter=pandoc-crossref
            - --reference-doc=word_template_apa7.docx
            - --csl=Extras/clinical-biochemistry.csl
            - --citation-abbreviations=Extras/abbreviations.json
            - --lua-filter=Extras/scholarly-metadata.lua
            - --lua-filter=Extras/author-info-blocks.lua
        keep-ipynb: true
        keep-md: true
        keep_tex:  true
        number_sections: true
    bookdown::latex_document2:
        pandoc_args:
            - --csl=apa.csl
            - --filter=pandoc-crossref
            - --reference-doc=word_template_apa7.docx
            - --csl=Extras/clinical-biochemistry.csl
            - --citation-abbreviations=Extras/abbreviations.json
            - --lua-filter=Extras/scholarly-metadata.lua
            - --lua-filter=Extras/author-info-blocks.lua
        keep-ipynb: true
        keep-md: true
        keep_tex:  true
        number_sections: true
csl: apa.csl
bibliography: references.bib
bibtex: references.bib
link-citations: true
citations-hover: true
toc: false
cap-location: top
latex-auto-mk: true
header-includes:
    - \usepackage{fontspec}
    - \setmainfont{Times New Roman}
    - \usepackage{graphicx}
    - \usepackage{float}
    - \usepackage{longtable}
    - \setlength\parindent{24pt}
    - \usepackage{gb4e} \noautomath
    - \usepackage[longtable]{multirow}
    - \usepackage{longtable}[=v4.13]
    - \usepackage[flushleft]{threeparttable}
    - \usepackage{lscape}
    - \usepackage{makecell}
    - \usepackage{booktabs}
    - \usepackage{sectsty} \sectionfont{\centering \emph}
    - \usepackage{fontspec}
    - \setmainfont{Times New Roman}
    - \usepackage{booktabs}
    - \usepackage{array}
    - \usepackage{multirow}
    - \usepackage[table]{xcolor}
    - \usepackage{wrapfig}
    - \usepackage{colortbl}
    - \usepackage{pdflscape}
    - \usepackage{tabu}
    - \usepackage{threeparttable}
    - \usepackage[normalem]{ulem}
---

Scholars have long documented the influence of interpersonal bias in candidate recruitment, particularly with regard to job seekers' gender and age [@beattie2012PossibleUnconsciousBias; @heilman2012GenderStereotypesWorkplace; @paleari2019WhenPrejudiceYou]. This influence is observable during active candidate sourcing where job advertisements represent the first touchpoint in employer communication [@RynesS.1989]. These job ads can signal essential value-related information about an organization [@decooman2012PortrayingFittingValues] but can also determine the pool of potential candidates who apply for an advertised position and reinforce existing interpersonal biases. On the micro-level, job ads and the HR decisions that dictate their content are informed by the type of candidate employers explicitly or implicitly envision as "ideal" for a position [@kelly2010GenderedChallengeGendered]. @vanselm2021SearchOlderWorker, for instance, found that job ads targeting older workers contained frames consistent with general stereotypes of older individuals. On the meso-level, the content of job ads can also reflect the level of segregation (homogeneity), or lack thereof (heterogeneity), in an occupation. @gaucher2011EvidenceThatGendered found, job ads from traditionally male-dominated occupations such as engineer, plumber, and security guard tend to contain terms such as competitive, leader, ambitious, and similar wordings that are culturally related to masculinity, consequently making such ads less appealing to female candidates.

Thus far, limited research has explored the relationship between the content of job advertisements and macro-level occupational segregation, i.e., at the sectoral level, demarcated specifically by social category composition [with the exception of @garcia-retamero2006PrejudiceWomenMalecongenial; as cited in @clarke2020GenderStereotypesGenderTyped]. Although career changes across sectors are more common than ones across occupations [@carrillo-tudela_extent_2016], studies show workers generally tend to stay within social category-typed job domains due to a backlash effect [@fritsch_horizontal_2020]. Sectoral segregation demarcated based on social category composition may thus be more persistent and present a higher social barrier to entry than segregation demarcated based on other occupational factors, thus becoming key to understanding possible inequity in candidate sourcing.

Given this, the present study makes three main contributions. First, it investigates candidate sourcing in Dutch intranational sectors that are heterogeneous and homogenous in gender and age composition, i.e., female- and male-dominated vs. mixed-gender sectors and older worker- and younger worker-dominated vs. mixed-age sectors respectively (see Table 10). We take a communication perspective and specifically examine the extent to which framed gender- and age-related stereotypes are present in online job ads from heterogeneous and homogenous sectors. Second, it presents a systematic operationalization of broad-level gender- and age-related stereotypical frames in job ads. Employing the social categorization framing hypothesis [@Yang2015a], we adopt the conceptualization of pancultural and generalizable warmth- and competence-related social category stereotypes put forth in the stereotype content model [SCM\; @fiske2002ModelOftenMixed]. Third, we utilize a rigorous automated content analysis method that leverages holistic singular assessment coding and word vector representations as embeddings for supervised binary classification [@carducci_twitpersonality_2018]. This study thus seeks to answer the question: *to what extent are job advertisements from different occupational sectors framed in terms of warmth- and competence-based gender and age stereotypes?*

## Framing Theory and Stereotypical Frames {#framing}

Framing a message constrains its audiences to desired and meaningful interpretations by directing attention to information judged to be important by the message sender. Frames make salient some aspects or subset of possible considerations about a subject over others [@entman1993FramingClarificationFractured], typically through strategic "selection, emphasis, exclusion, and elaboration" [@reese2001FramingPublicLife, p. 10]. Within framing theory, stereotypes are a powerful framing device underscored by culturally embedded implicit reasoning devices [@vangorp2005WhereFrameVictims], i.e., they draw on and activate culturally shared (consensual) cognitive schemata. In their capacity as framing devices, stereotypes draw attention to a particular assessment of social categories, their roles, and their distance from the reader, thus stereotypes may come to define a frame.

Expounding on the use of stereotypes in framing, [@Yang2015a] presents a typology of stereotypical frame genres differentiated through their effects on individual cognition, and the pathway by which they make salient the perceived social distance between categories, i.e., degree of emphasis on the self-to-other differences. *Social categorization* frames in particular are germane to the current study as their usage centers around ownership of cultural objects such as social roles or certain jobs and occupational sectors. By emphasizing the belongingness of cultural objects to select social categories, social categorization frames activate distinct social identities, otherization, and make salient the social distance between social categories. This frame genre thus conveys the reasoning that "certain groups are outgroups and their members are not qualified for ingroup activities" [@Yang2015a, p. 261]. Likewise, social categorization frames may activate self-stereotyping and lead to ingroup members assuming the characteristics stereotypically associated with their category, increasing conformity and deindividuation [@brown2003BlackwellHandbookSocial].

Social categorization frames are also applied differently to different categories depending on whether they are dominant or non-dominant in a domain. When addressing dominant social categories, emphasis is placed on ingroup characteristics and their complementarity to features of the cultural object. When addressing outgroups, the information also tends to be stereotype-consistent, however, the emphasis is on the mismatch between the cultural object and the categories' characteristics. Examples of social categorization framing include female political candidates being framed as intruders and a novelty in political races by the news media [@meeks_all_2013; @sullivan19891984VicePresidential] and female athletes being depicted as aliens and given minor roles in the sports coverage [@hardin2002FramingSexualDifference]. Applied to job ads wherein messages are targeted to perceived ideal candidates, frames in job ads from sectors that are "owned" by a single social category, i.e., from a homogeneous sector, are likely to emphasize characteristics perceived as essential to the dominant social category.

## Stereotype Content Model (SCM) {#scm}

Examining consensual stereotypes, i.e., stereotypes that are (perceived to be) shared by the wider culture [@Zanna2013], @beukeboom2019HowStereotypesAre describe stereotype content as the "[cognitive] representation people hold about a social category, consisting of beliefs and expectancies about probable behaviors, features, and traits" (p. 9). The extent to which stereotype content is endorsed depends on the strength of individual essentialist beliefs about the stereotyped category [for perceived category essentialism and stereotyping, see @beukeboom2019HowStereotypesAre; @bastian2006PsychologicalEssentialismStereotype].

Specific stereotypes about both gender and age categories can vary across cultures and within different strata of the same culture. One model that circumvents this barrier is the *stereotype content model* (SCM) as it is suitable for investigating pancultural, superordinate, and broad-level stereotypes. Developed by @fiske2002ModelOftenMixed, the SCM provides a universal principle determining predictors of stereotypes and sets up a framework to comparatively and systematically investigate stereotype content [@kroon2018ReliableUnproductiveStereotypes; @vanselm2021SearchOlderWorker]. Due to its generalizability and intuitiveness, the SCM has been routinely used by scholars to analyze intergroup communication, media, and text for markers of other- as well as self-stereotyping [@westerhof2010FillingMissingLink; @white2009ThinkWomenThink]. In recruitment, @hofhuis2016DealingDifferencesImpact relate warmth and competence perceptions to social and task-performance ratings HR managers assigned to job candidates. In textual data analysis, the SCM's applications have extended into computational research as a framework for stereotype- and bias-detection natural language models [@nicolas2020ComprehensiveStereotypeContent].

The SCM differentiates pancultural stereotype content along two perceptual dimensions: *warmth* and *competence* [@cuddy2009StereotypeContentModel]. Perceived warmth is related to compassion, kindness, helpfulness, and interpersonal sensitivity whereas perceived competence is associated with self-assertion, leadership, analytical thinking, and independence [for a list of traits, see @bruckmuller2013DensityBigTwo; @Carli2016; @hummert1990MultipleStereotypesElderly]. The assessments of outgroup members along these two dimensions form the core of social category stereotypes including ingroup self-stereotypes [@hinton2019ExploringRelationshipGay].

According to the SCM, gender groups are social categories that are subject to cross-cultural stereotyping along the dimensions of warmth and competence [@fiske2002ModelOftenMixed]. Females (and women generally) are linked to warmth traits but perceived as low in competence whereas males (and men generally) are linked to competence traits but perceived as low in warmth [@Eagly1997; @suh2004GenderRelationshipsInfluences]. Different age groups also have associated warmth- and competence-related stereotypes: older individuals are perceived as lacking in competence compared to their younger counterparts but generally rated higher on warmth whereas younger individuals are perceived as lacking in warmth but consistently rated higher on competence [@cuddy2005ThisOldStereotype; @vanselm2021SearchOlderWorker].

### Gender Stereotypes in the Occupational Domain {#gender}

The stereotypical attribution of warmth and competence to females and males also form the basis for stereotypes about female and male workers [@froehlich2020GenderWorkNations] and is further generalizable to gendered occupational domains. Various studies point to the observability of gendered warmth and competence stereotype differences in different contexts and when employing different analytical approaches [@aaldering2020PoliticalLeadershipMedia; @harmer_are_2017]. @smith2019PowerLanguageGender found that positive attribute assignments to female and male leaders were aligned with the SCM, however, female leaders were also attributed more negative warmth characteristics compared to their male counterparts. These findings implicitly provide evidence for social categorization framing. Dominant social groups with stereotyped characteristics matching (and seen as essential to) a social role are appraised based on said characteristics whereas non-dominant groups with mismatching stereotyped characteristics are appraised via both characteristics of the social role and the social group -- the latter often resulting in unfavorable appraisal.

Particular to occupational segregation, a survey by @he2019StereotypesWorkOccupational on warmth and competence perception associated with different occupations found a positive correlation between occupational stereotype content and the respective level of gender segregation. Nursing, medical assistance, childcare, and secretarial work were the highest-rated occupations on warmth, and women made up the majority in these occupations: 89.4%, 90.7%, 94.9%, and 94.5% respectively. Similarly, @strinic2021OccupationalStereotypesProfessionals, in a survey using a sample of 130 HR professionals, found that stereotypical perceptions of warmth and competence are in fact attached to occupations and sectors.

In light of the reviewed literature, we expect similar differences in the presence of warmth- and competence-related stereotypical frames in job ads at the sectoral level:

> **Hypothesis 1:** Job advertisements from female-dominated sectors will include more warmth-related frames when compared to job advertisements from male-dominated sectors **(H1a)** or mixed-gender sectors **(H1b)**.

> **Hypothesis 2:** Job advertisements from male-dominated sectors will include more competence-related frames when compared to job advertisements from female-dominated sectors **(H2a)** or mixed-gender sectors **(H2b)**.

### Age Stereotypes in the Occupational Domain {#age}

Stereotypical attribution of warmth and competence to workers from different age groups also aligns with the general stereotypes of individuals in those categories. In a frame analysis study of Dutch media texts published over the span of six years, @kroon2018ReliableUnproductiveStereotypes found that both corporate and news media portray older workers as trustworthy, involved, and committed (warmth characteristics) but lacking in aptitudes related to productivity, adaptability, and technological skills (competence characteristics). @krings2011StereotypicalInferencesMediators also found that good-naturedness, amicability, benevolence, and sincerity formed the content of warmth-related stereotypes for older workers while capability, efficiency, and skill formed the content of competence-related stereotypes for younger workers.

In job ads, different contextual factors seem to be at play. @vanselm2021SearchOlderWorker found hard abilities requirements for general job seekers (e.g., business operations, leadership, and professional development abilities) were more pronounced compared to soft abilities requirements for older workers (e.g., customer service ability). This emphasis on competence over warmth was also noted in a study by @abrams2016OldUnemployableHow where role congruity between a job's age-type and an older candidate's stereotyped characteristics did not increase older candidate selection. Findings point to an undervaluing of older workers' warmth characteristics and indicate warmth-primacy -- wherein proneness to evaluate others positively is predicted primarily by warmth perceptions [@cuddy2008WarmthCompetenceUniversal; @ponsi2016InfluenceWarmthCompetence] -- functions differently in the context of age-typed recruitment.

Literature thus suggests that when comparing job ads from older-worker-dominated and younger-worker-dominated sectors, the presence of competence-related frames may be more relevant to determining whether bias against older workers (or in favor of younger workers) may exist. Notwithstanding, as social stereotypes about older individuals form the basis for older-worker stereotypes, we expect:

> **Hypothesis 3:** Job advertisements from sectors dominated by older workers will include more warmth-related frames when compared to job advertisements from sectors dominated by younger workers **(H3a)** or mixed-age sectors **(H3b)**.

> **Hypothesis 4:** Job advertisements from sectors dominated by younger workers will include more competence-related frames when compared to job advertisements from sectors dominated by older workers **(H4a)** or mixed-age sectors **(H4b)**.

## Methodology {#method}

### Data Collection and Sample {#sampling}

Job ads were collected based on searches for sectors keywords from three online job search platforms: LinkedIn.nl, Indeed.nl, and Glassdoor.nl . Search keywords for sectors were obtained from the one-digit International Standard Industrial Classifications [@centraal_bureau_voor_de_statistiek_standard_2018]. Some of the original 29 SBI sector titles were a combination of multiple independent sector designations, e.g., "agriculture, forestry and fishing". These sector titles returned imprecise search results and were thus divided into distinct sector search keywords and the resultant list of sectors keywords was supplemented with data from the more detailed standardized 5-digit SBI codes and the Dutch Labour Force Survey [@centraal_bureau_voor_de_statistiek_dutch_2021]. This gave a total of 97 sector-keywords, and all returned job postings were automatically retrieved using Python 3.9 (see Table 9 in Appendix A).

## References
