---
title             : "Bias in Candidate Sourcing Communication\:
Investigating Stereotypical Gender- And Age-Related Frames in Online Job Advertisements at the Sectoral Level"
"
shorttitle        : "Bias in Candidate Sourcing Communication"

author:
  - name          : "M.F.A. Noon"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Postbus 15791, 1001 NG Amsterdam"
    email         : "noon.abdulqadir@uva.nl"
    role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
      - "Conceptualization"
      - "Writing - Original Draft Preparation"
      - "Writing - Review & Editing"
  - name          : "Anne Kroon"
    affiliation   : "1"
    role:
      - "Writing - Review & Editing"
      - "Supervision"
  - name          : "Martine van Selm"
    affiliation   : "2"
    role:
      - "Writing - Review & Editing"
      - "Supervision"
  - name          : "Margot van der Goot"
    affiliation   : "1"
    role:
      - "Writing - Review & Editing"
      - "Supervision"
  - name          : "Rens Vliegenthart"
    affiliation   : "1"
    role:
      - "Writing - Review & Editing"
      - "Supervision"

affiliation:
  - id            : "1"
    institution   : "Amsterdam School of Communication Research (ASCoR)"
  - id            : "2"
    institution   : "Erasmus School of History, Culture and Communication"

authornote: |
  Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.

  Enter author note here.

abstract: |
  Studies show that the extent to which job advertisements contain stereotypical wordings correlates with the level of segregation in an occupational domain. However, limited research links the framing of job ads to social category-based occupational segregation at the macro sectoral level. Guided by the stereotype content model, the present study operationalizes stereotypical social categorization frames in candidate sourcing communication and investigates their presence in job ads from occupational sectors with varying gender and age segregation. An automated (supervised) content analysis was conducted on a dataset of online job ads (n=17,050). Results indicate warmth-related frames are most observed in ads from female-dominated (vs. male-dominated and mixed-gender) sectors. Conversely, competence-related frames are most observed in ads from male-dominated (vs. female-dominated) and younger worker-dominated (vs. older worker-dominated and mixed-age) sectors. Taken together, we present an operationalization of stereotypical warmth- and competence-related frames in early employer communication and posit that social categorization framing may be at play.

  <!-- https://tinyurl.com/ybremelq -->

keywords          : "Stereotype content model, social categorization frames, horizontal occupational segregation, supervised content analysis"
wordcount         : "X"

bibliography      : "references.bib"

floatsintext      : no
linenumbers       : yes
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no

classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library("papaja")
r_refs("references.bib")
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```

# Methods

We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

## Material

## Procedure

## Data analysis

We used `r cite_r("references.bib")` for all our analyses.

# Results

# Discussion

\newpage

# References

::: {#refs custom-style="Bibliography"}
:::
